# Required - see: https://github.com/kubernetes/kops/pull/2949#issuecomment-321752139
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ template "fullname" . }}
  labels: {{- include "labels.standard" . | nindent 4 }}
rules:
  # Allow Dashboard to read all core api objects except secrets
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["delete", "list"]
  nonResourceURLs: []
